spring.application.name=africanOracle

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:africanOracle

spring.ai.openai.api-key=${OPENAI_API_KEY};
spring.ai.openai.chat.options.model=gpt-4o;
